language: csharp
sudo: false
mono:
  - beta
env:
  - MONO_THREADS_PER_CPU=2000 MONO_MANAGED_WATCHER=disabled
os:
  - linux
  - osx
before_script:
  - chmod +x build.sh
script:
  - ./build.sh --quiet verify
